version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: chat-frontend
    ports:
      - "8080:80"
    environment:
      - VITE_SOCKET_URL=http://localhost:3000
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: chat-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: chat-redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:stable-alpine
    container_name: chat-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
